### ISSUE TITLE
A question about rendering code

### ISSUE THREAD

**Issue by cuizhiling** [mworchel/svbrdf-estimation#44]
Thank you very much for providing open source code, but why is there color difference in the picture rerendered by the rendering program? How can I solve it?

**Comment by mworchel** [comment]
Hi,

between which images do you see a difference? The rendered image and the images in the sample data? The renderer outputs are in linear RGB and need to be converted to (approximate) sRGB for display, for example with `utils.gamma_encode`.

**Comment by cuizhiling** [comment]
I tried to run the main function in the file(renderers.py)  to render the picture in the dataset(single-view dataset ~80GB) provided by Deschaintre. I noticed that the function utils.gamma_encode has been used to process the displayed image, but there is still a color difference between the rerendered image and the Ground Truth. For example, when I input the image(0000237;metal_painted_barrelXPW_ConcreteWall001;2X3.png) into this program, the result is :
![V`5UE2V4PK_P(6{GO5TR47R](https://user-images.githubusercontent.com/49269587/162575256-bd987746-5087-4ead-91e3-78ab222938da.png)
The original color of the material should be brown, but the picture rerendered according to the four attributes (normals, diffuse, roughness, special) is yellow.

**Comment by mworchel** [comment]
I currently don't have the single-view dataset at hand. Could you zip the sample for me? 

Btw, this is my output for the samples:
![grafik](https://user-images.githubusercontent.com/9449513/162575715-d9c88d08-b54e-410d-81f8-f7c7910a95cd.png)

**Comment by cuizhiling** [comment]
This dataset comes from the links provided on your project homepage(README.md - Implementation Details). I randomly selected 20 pictures in this dataset and put them in [https://github.com/cuizhiling/BRDF/blob/main/dataset(20%20images).rar ](url) , which you can download directly,

**Comment by mworchel** [comment]
Thanks, I couldn't access the URL but I noticed I still have the dataset.

I think I remember what the issue is: The renderings in the single-view dataset are not in sRGB but linear RGB. The `SvbrdfDataset` class has a initializer argument to handle this case (`is_linear`). By default, this flag is `False` but in your case you need to set it to `True` so that the images are properly read.

With `is_linear=True` and a little bit of light adjustments, I get this:
![grafik](https://user-images.githubusercontent.com/9449513/162576438-e349115a-1c12-4900-a146-598c63f137a8.png)
